create_charge_schedule:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: mazda_6e
    start_time:
      required: true
      example: "01:00"
      selector:
        time:
    end_time:
      example: "06:00"
      selector:
        time:

delete_charge_schedule:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: mazda_6e

create_battery_preheating:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: mazda_6e
    departure_time:
      required: true
      example: "07:30"
      selector:
        time:

delete_battery_preheating:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: mazda_6e
